# wget https://storage.googlespis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kube-scheduler
# kube-scheduler.service
# --scheduler-name=default-scheduler
# --scheduler-name=my-custom-scheduler


# Create a custom scheduler
apiVersion: v1
kind: Pod
metadata:
  name: my-custom-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler 
    - --address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    - --scheduler-name=my-custom-scheduler
    image: k8s.gcr.io/kube-scheduler-amd64:v1.11.3
    name: kube-scheduler

# kubectl get events


---
# Create a pod using the above created custom scheduler  
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - image: nginx
    name: nginx-container
  schedulerName: my-custom-scheduler