apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name:  nginx-container
    image: nginx
    ports:
    - containerPort: 8080
    envFrom:
      - secretRef:
        name: app-config
    env:
      - name: DB_Password
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: DB_Password
    volumes:
    - name: app-secret-volume
      secret: 
        secretName: app-secret

#/**********************************************/        
# If secrets mounted as volumes then they can be found at,
# cd /opt/app-secret-volumes/ 