# By default service would be of type cluster ip
apiVersion: v1
kind: Service
metdata:
  name: myapp-clusterip-service
spec:
  type: ClusterIP # not mandatory since it is default
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: myapp
    type: back-end
    
