apiVersion: apps/v1
kind:  DaemonSet
metadata:
  name: monitoring-daemon
spec:
  selector:
    matchLabels:
      app: monitoring-agent
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      containers:
        - image: monitoring-agent
          name: monitoring-agent

# To get daemonset spec run a deployement dry-run and edit it          