apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: myapp-container
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In  # or operator: Exists
            values:
            - Large  
          - key: size
            operator: NotIn
            values:
            - Small
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
          matchExpressions:
          - key: size
            operator: In
            values:
            - Large

# Node Affinity Types
# requiredDuringSchedulingIgnoredDuringExecution
# preferredDuringSchedulingIgnoredDuringExecution

