apiVersion: v1
kind: Pod
metdata:
  name: myapp-pod
  labels:
    type:front-end
spec:
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"

# kubectl taint nodes node-name key=value:taint-effect    # taint-effect are NoSchedule | PreferNoSchedule | NoExecute
# kubectl taint nodes node1 app=blue:NoSchedule 
# kubectl describe node <node name> | grep Taint
# kubectl taint nodes node1 key1=value1:NoSchedule-       # to remove taint from a node

# kubectl explain pod --recursive | less
# kubectl explain pod --recursive | grep -A5 tolerations



