apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleep-pod
spec:
  containers:
    - name: ubuntu-sleep-container
      image: ubuntu-sleep
      command: ["sleepv2"]        #maps to ENTRYPOINT of docker
      args: ["10"]                #maps to CMD of docker
    - name: ubuntu-sleep-container2
      image: ubuntu-sleep
      command:
        - "sleep"
        - "1200" 
    - name: ubuntu-sleep-container3
      image: ubuntu-sleep
      command: ["sleep","5000"]