# Static Provisioning
    - create a persistent disk on GCP
    - create a PV 

# Dynamic Provisioning
    - creta a storage class definition
    - provide it in pvc definition

# sc.definition.yaml
apiVersion: v1
kind: StorageClass
metadata:
    name: google-storage
provisioner: kubernetes.io/gcp-pd
parameters:
    type: pd-standard       # [ pd-standard | pd-ssd]
    replication-type: none  # [ none | regional-pd ]


# pvc-definition.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: myclaim
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: google-storage
    resources:
        requests:
            storage: 500Mi

