apiVersion: v1
kind: Service
metdata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80          # mandatory
      nodePort: 30008   #30000-32767
  selector:
    app: myapp
    type: front-end

